### ISSUE TITLE
Call to undefined function

### ISSUE THREAD

**Issue by sebbo2002** [fanningert/webtrees_simpleautologin#5]
I tried to install your plugin on a Webtrees 2.2.0 instance (set up using [this Docker container](https://docker.io/nathanvaughn/webtrees)). Unfortunately I'm unable to enable the module, as I get this error message after installing it to the `modules_v4` directory:

```
Error: Call to undefined function at\fanninger\WebtreesModules\SimpleAutoLogin\Modules\app() in /var/www/webtrees/modules_v4/webtrees_simpleautologin/src/Modules/SimpleAutoLoginModule.php:40
Stack trace:
#0 /var/www/webtrees/app/Services/ModuleService.php(887): at\fanninger\WebtreesModules\SimpleAutoLogin\Modules\SimpleAutoLoginModule->boot()
#1 /var/www/webtrees/app/Http/Middleware/BootModules.php(56): Fisharebest\Webtrees\Services\ModuleService->bootModules(Object(Primer\PrimerTheme))
#2 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#3 /var/www/webtrees/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#4 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#5 /var/www/webtrees/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#6 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#7 /var/www/webtrees/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#8 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#9 /var/www/webtrees/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#10 /var/www/webtrees/vendor/illuminate/database/Concerns/ManagesTransactions.php(32): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection))
#11 /var/www/webtrees/app/Http/Middleware/UseTransaction.php(44): Illuminate\Database\Connection->transaction(Object(Closure), 3)
#12 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#13 /var/www/webtrees/app/Http/Middleware/DoHousekeeping.php(71): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#14 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#15 /var/www/webtrees/app/Http/Middleware/UseTheme.php(66): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#16 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#17 /var/www/webtrees/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#18 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#19 /var/www/webtrees/app/Http/Middleware/UseLanguage.php(69): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#20 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#21 /var/www/webtrees/app/Http/Middleware/UseSession.php(79): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#22 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#23 /var/www/webtrees/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#24 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#25 /var/www/webtrees/app/Http/Middleware/UseDatabase.php(60): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#26 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#27 /var/www/webtrees/app/Http/Middleware/BadBotBlocker.php(308): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#28 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#29 /var/www/webtrees/app/Http/Middleware/CompressResponse.php(71): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#30 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#31 /var/www/webtrees/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#32 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#33 /var/www/webtrees/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#34 /var/www/webtrees/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#35 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#36 /var/www/webtrees/app/Http/Middleware/PublicFiles.php(62): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#37 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PublicFiles->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#38 /var/www/webtrees/app/Http/Middleware/HandleExceptions.php(89): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#39 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#40 /var/www/webtrees/app/Http/Middleware/SecurityHeaders.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#41 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#42 /var/www/webtrees/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#43 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#44 /var/www/webtrees/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#45 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#46 /var/www/webtrees/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#47 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#48 /var/www/webtrees/app/Http/Middleware/ErrorHandler.php(38): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#49 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ErrorHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#50 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#51 /var/www/webtrees/app/Webtrees.php(280): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#52 /var/www/webtrees/app/Webtrees.php(251): Fisharebest\Webtrees\Webtrees->httpRequest()
#53 /var/www/webtrees/index.php(24): Fisharebest\Webtrees\Webtrees->run('apache2handler')
#54 {main}
```

I already tried to remove all other modules, but did not help. Any ideas what I am doing wrong?

**Comment by AlexBocken** [comment]
I can confirm that I have the same issue when updating to webtrees 2.2.0. removing any other packages and re-installing this package did not change anything. Please let me know if I can help in triage somehow, I'm happy to provide anything necessary.

**Comment by arbor95** [comment]
reason / solution is compatibilty with 2.2:
change app( to Registry::container()->get( and insert use Fisharebest\Webtrees\Registry;

**Comment by AlexBocken** [comment]
@arbor95 Thanks for the hints! I've found your forum posts on this. Turns out it was a bit more complicated than simply exchanging these functions as we have to rebind some classes. I've found an approach in https://github.com/miqrogroove/family-tree-home which we could re-use and got a functioning build for 2.2 and 2.1 working. Will open a PR

**Comment by JackPala** [comment]
I have this issue too. Will try your fix commit

**Comment by JackPala** [comment]
It appears pulling the @AlexBocken repo allows this to work on 2.2.x for me as well
